<?php

namespace Naykel\Gotime\Components;

use Illuminate\Support\Facades\Blade;
use Illuminate\View\Component;

class Markdown extends Component
{
    /**
     * Raw markdown file content loaded from disk
     */
    protected string $file;

    /**
     * Processed HTML content (without TOC)
     */
    protected string $content;

    /**
     * Extracted table of contents HTML
     */
    protected string $toc = '';

    public function __construct(
        protected string $path,             // resource/views path excluding extension
        protected string $fullPath = ''     // full path excluding extension. allows absolute paths
    ) {
        if (! empty($fullPath)) {
            $this->file = getFile($this->fullPath . '.md');
        } else {
            $this->file = getFile($this->path . '.md');
        }

        // Convert markdown to HTML and prepare for rendering
        $this->processMarkdown();
    }

    /**
     * Converts raw markdown to HTML and structures it for display.
     *
     * This method:
     * 1. Renders the markdown file to HTML using the @markdown Blade directive
     * 2. Searches for a table of contents (TOC) generated by CommonMark extension
     * 3. If TOC exists: extracts it and places it before the main content
     * 4. Wraps the main content in a .markdown-content div for styling
     *
     * The result is stored in $renderedContent, ready to pass to the view.
     *
     * Why? Processing here (instead of in the view) allows us to:
     * - Manipulate the HTML structure (extract TOC, wrap content) before
     *   rendering making it easier to style and control layout
     * - Separate concerns: component handles logic, view handles display
     */
    protected function processMarkdown(): void
    {
        $rendered = Blade::render('@markdown($file)', ['file' => $this->file]);
        
        // Extract TOC by finding the complete nested structure
        $extractedToc = $this->extractToc($rendered);
        
        if ($extractedToc) {
            $this->toc = $extractedToc;
            $this->content = str_replace($extractedToc, '', $rendered);
        } else {
            $this->content = $rendered;
        }
    }

    /**
     * Extract the table-of-contents element with proper nested tag handling.
     * Supports both new format (<ul class="toc">) and old format (<div data-toc>)
     */
    protected function extractToc(string $html): ?string
    {
        // Try new format first: <ul class="toc">
        $toc = $this->extractNestedTag($html, 'ul', 'class="[^"]*toc[^"]*"');
        
        // Fall back to old format: <div data-toc>
        if (!$toc) {
            $toc = $this->extractNestedTag($html, 'div', 'data-toc');
        }
        
        return $toc;
    }

    /**
     * Extract a nested HTML tag with specific attribute pattern
     */
    protected function extractNestedTag(string $html, string $tag, string $attrPattern): ?string
    {
        // Find opening tag with specified attribute
        $pattern = '/<' . $tag . '[^>]*' . $attrPattern . '[^>]*>/';
        
        if (!preg_match($pattern, $html, $match, PREG_OFFSET_CAPTURE)) {
            return null;
        }

        $start = $match[0][1];
        $pos = $start + strlen($match[0][0]);
        $depth = 1;

        // Count nested tags to find the matching closing tag
        $openPattern = '<' . $tag;
        $closePattern = '</' . $tag . '>';
        
        while ($pos < strlen($html) && $depth > 0) {
            $nextOpen = strpos($html, $openPattern, $pos);
            $nextClose = strpos($html, $closePattern, $pos);

            if ($nextClose === false) {
                // Malformed HTML - couldn't find closing tag
                return null;
            }

            if ($nextOpen !== false && $nextOpen < $nextClose) {
                $depth++;
                $pos = $nextOpen + strlen($openPattern);
            } else {
                $depth--;
                $pos = $nextClose + strlen($closePattern);
            }
        }

        return $depth === 0 ? substr($html, $start, $pos - $start) : null;
    }

    public function render()
    {
        return view('gotime::components.markdown')->with([
            'content' => $this->content,
            'toc' => $this->toc,
        ]);
    }
}
